### ISSUE TITLE
batch edit bugs

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#1222]
- [ ] when c4k info is missing in batch edit form #1225 

- [ ] c4k cert field warning styling #1227 
- [ ] multiple family determination w/ missing info in batch edit #1228 

- [ ] Some weirdness remains with the cycling-thru-enrollments and landing on the all complete no-selected-item-content, but may be due to some of the above bugs or https://github.com/ctoec/ecis-experimental/issues/1207 bug so holding off on ticket until those are addressed
