### ISSUE TITLE
Pre-pilot checklist

### ISSUE THREAD

**Issue by abbyraskin** [ctoec/ecis-experimental#229]
#### Data collection
- [x] Clean up data collection document 
- [x] Sync with Julie on open data collection questions
- [x] Recommend withdrawal reasons
- [x] Socialize [data collection recommendations](https://docs.google.com/document/d/17XrX7esGluXJZNRcK-V9E_KFEzLd4hSoZhTvFXfCyuA/edit) with Rachel, to faciliate with additional OEC folks for decision making
- [x] Get OEC approval on data collection recommendations #315 
- [x] Finalize pilot PSR (requires data collection approval) #140

#### Starter data for pilot sites
- [x] Obtain ECIS starter data (blocked)
- [x] Request last three months of PSRs for pilot sites #378 
- [x] Program data from contracts #431 
- [ ] (Test functionality with actual site data!)

#### Legal
- [x] Get OEC legal approval and language for licensing and confidentiality agreement (see: #267) 

#### Other
- [x] Pick a name!
- [ ] Figure out if any starter sites have non-US birth certificates

***

#### Recruiting pilot sites
- [x] OEC to send pilot invitations - target date: December 9 #316 
- [x] Send welcome/info emails to confirmed pilot sites ahead of launch (user accounts, scheduling, onboarding info) #319 

#### Onboarding 
 - [x] Create onboarding one-pager #318 

#### Pilot monitoring
- [x] Troubleshooting feedback during pilot - shared mailbox; Abby and Chris on deck to monitor issues

***

### Tech
- [x] Create user accounts #282
- [x] Quick fixes, ideally ahead of launch #219
