### ISSUE TITLE
update queries to use new custom hooks

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#235]
blocked by #234

- [x] #236 - App container
- [x] #237 - Roster container
- [x] #238 - Reports container
- [x] #239 - ReportDetail container
- [x] #240 - Enrollment/Edit container
- [x] #241 - Enrollment/Detail container
- [x] #242 - Enrollment/New container
