### ISSUE TITLE
multi-site [mega checklist]

### ISSUE THREAD

**Issue by mmazanec22** [ctoec/ecis-experimental#332]
- ~[ ] get all enrollments for an organization (#651)~
- [x] frontend to make multiple enrollment queries (#688)
- ~[ ] update site id on enrollment (do we need to delete and recreate ?) -- do we need to do this, or will we always be withdrawing from one site, and then starting new enrollment on a different site ?~ (EDIT: Punt on this for now) 
- [x] refactor `getIdForUser` (#655)
- [x] refactor enrollment flow (#654 )
- [x] enable user to switch between all sites or single-site roster (#652 )
- [x] user selects a site for enrollment before starting enrollment from all-sites roster view (#656)

**Comment by abbyraskin** [comment]
(@jlhogan assigning to you for now to break out tech tasks per sync this AM)
