### ISSUE TITLE
QA checklist 12/10

### ISSUE THREAD

**Issue by atreni** [ctoec/ecis-experimental#390]
Reviewed staging site with Julia on 12/10 and discussed the following items:

Roster (see screenshots below)
- [x] align “enroll child” CTA with program title (#392 )
- [x] add a count to missing information label in legend (#393 )
- [x] spacing and alignment tweaks to roster view (#394)

Reports
- [x] back to reports link styling (#395)
- new line for dates in CDC report title

Summary page
- back to roster link styling (#395) (listed above)
- [ ] styling of missing information alerts (#397)
- [x] decrease text leading in child detail view subsections (#396)

**Comment by cmgiven** [comment]
Closing. Only #397 remains open.
