### ISSUE TITLE
Convert old tests from Enzyme to RTL

### ISSUE THREAD

**Issue by cailyncodes** [ctoec/ecis-experimental#682]
Tests:
- [x] Component folder (@cailyncodes) (PR: #701)
- [x] App (@cailyncodes) (PR: #705)
- [x] Roster (@cailyncodes) (PR:  #706)
- [x] Enrollment[Edit|Detail] (@mmazanec22 ) (PR: #711)
- [x] ReportsSummary (@cmgiven) (PR: #714)
- [x] ReportDetail folder (@cmgiven) (PR: #714)

**Comment by cailyncodes** [comment]
Constituent PRs merged in!
