### ISSUE TITLE
Part-time/full-time splits

### ISSUE THREAD

**Issue by cmgiven** [ctoec/ecis-experimental#889]
## Schema

- [x] Fundings are associated with FundingSpaces (#858)
- [x] FundingSpaces support part-time/full-time splits (#876)

## UI

- [x] ChoiceList with additional options (#890)
- [x] Currency numerals on report vertically align (#891)

## Roster

- [x] Funding tags only show "PT"/"FT" when needed (#892)
- [x] Legends use FundingSpaces consistently (#893) _needs ac_

## Enrollment flow

- [x] Funding interface selects from available funding spaces (#894)

## Report

- [x] Report records part-time/full-time weeks (#895)
- [x] Report shows "weeks remaining" of part-time or full-time splits (#901)
- [x] Utilization table calculates and displays part-time/full-time weeks (#896)
