### ISSUE TITLE
Refactor enrollment form sections

### ISSUE THREAD

**Issue by jlhogan** [ctoec/ecis-experimental#946]
**User story**: As a developer, I am able to instantiate individual form fieldsets/fields for every enrollment section (see history in https://github.com/ctoec/ecis-experimental/pull/1050 for examples)

**AC**:
- [x] child info fields #1102 
- [x] Family information fields are modular #1103
- [x] family income information fields use new Form context #1104 
- [x] Enrollment/funding fields are modular #1105
